version: '3.6'
networks:
  default:
    external:
      name: proxy
services:
  traefik:
    image: traefik:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
  ui:
    image: dbudnick/botmoc
    restart: always
    labels:
      - 'traefik.backend=ui'
      - 'traefik.docker.network=proxy'
      - 'traefik.frontend.rule=Host:botmoc.masterofcode.com'
      - 'traefik.enable=true'
      - 'traefik.port=3000'
      - 'traefik.default.protocol=http'
      - 'traefik.frontend.priority=10'
  backend:
    image: dbudnick/botmoc-api
    restart: always
    labels:
      - 'traefik.backend=be'
      - 'traefik.docker.network=proxy'
      - 'traefik.enable=true'
      - 'traefik.port=4000'
      - 'traefik.frontend.rule=PathPrefixStrip:/api/'
      - 'traefik.default.protocol=http'
      - 'traefik.frontend.priority=20'
    ports:
      - 4000:4000
    environment:
      SERVER_PORT: 3000
      NODE_ENV: production
      DB_HOSTNAME: postgres
      POSTGRES_USERNAME: botmoc
      # POSTGRES_PASSWORD: 
      POSTGRES_DB: botmoc
      DB_HOSTNAME: postgres
  postgres:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    labels:
      - 'traefik.postgres=postgres'
      - 'traefik.docker.network=proxy'
      - 'traefik.enable=true'
      - 'traefik.port=5432'
      - 'traefik.default.protocol=http'
    environment:
      POSTGRES_USER: botmoc
      # POSTGRES_PASSWORD: 
      POSTGRES_DB: botmoc