version: '3.6'
services:
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: botmoc
      POSTGRES_PASSWORD: botmoc
      POSTGRES_DB: botmoc
      DB_HOST: localhost
